---
title: "EBOLA Guinée - Tableau de bord - Date : "
date: "`r format(Sys.time(), '%A %d %B %Y')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(htmlwidgets)
library(flexdashboard)
library(sqldf)
library(formattable)
library(kableExtra)
require(dplyr)
library(ggplot2)
library(purrr)
library(data.table)
library(lubridate)
library(gganimate)
library(palettetown)
library(plotly)
library(aweek)
library(rio)

library(tidyr)
library(tibble)
library(stringr)

source(here::here("scripts", "analysis_preparation.R"))


```


```{r load_data, include = FALSE}

current_clean_cases <- here::here("data",
                                  "clean",
                                  "rds",
                                  "cases_clean.rds")

current_clean_contacts <- here::here("data",
                                      "clean",
                                     "rds",
                                      "contacts_clean.rds")


current_clean_relationships <- here::here("data",
                                          "clean",
                                          "rds",
                                          "relationships_clean.rds")

current_clean_followups <- here::here("data",
                                      "clean",
                                      "rds",
                                      "followups_clean.rds")

current_clean_events <- here::here("data",
                                      "clean",
                                      "rds",
                                      "events_clean.rds")


current_clean_users <- here::here("data",
                                      "clean",
                                      "rds",
                                      "users_clean.rds")

current_contacts_becoming_cases <- here::here("data",
                                      "clean",
                                      "rds",
                                      "contacts_becoming_cases_clean.rds")

current_teams <- here::here("data",
                                      "clean",
                                      "rds",
                                      "teams_clean.rds")


current_clean_cases <- import(current_clean_cases) %>%
  as_tibble()

current_clean_contacts <- import(current_clean_contacts) %>%
  as_tibble()

current_clean_relationships <- import(current_clean_relationships) %>%
  as_tibble()

current_clean_followups <- import(current_clean_followups) %>%
  as_tibble()

current_clean_events <- import(current_clean_events) %>%
  as_tibble()

current_clean_users <- import(current_clean_users) %>%
  as_tibble()

current_teams <- import(current_teams) %>%
  as_tibble()

current_contacts_becoming_cases <- import(current_contacts_becoming_cases) %>%
  as_tibble()


current_cases_probables_confirmes <- current_clean_cases %>%
  filter(classification=="confirmé" | classification=="probable")



#Import Shapefile 
#Process Shapefile & join to cases & contacts
#export shp to .shp folder in data/clean

#Get the file with the tables
source(here::here("report_sources", "ref_scripts_tables.R"))

```

```{r themes, include = FALSE}
# Create cusotmized color scales for graphs and tables
custom_green0 = "#E3FCEE"
custom_green = "#71CA97"
custom_red0 = "#FFAAAA"
custom_red = "#ff7f7f"
custom_grey0 = "#ADADAD"
custom_grey = "#818181"
custom_orange0 = "#FFD6CA"
custom_orange = "#FF9270"
custom_blue0 = "#79C5FF"
custom_blue = "#004F8B"
godata_orange = "#ff884d"
godata_green = "#4db0a0"

scale_status <- scale_fill_manual(
    "Statut",
    values = c(seen            = "#71CA97",
               not_seen        = "#5d6d75",
               not_performed   = "#D3C9C6",
               # seen_no_signs   = "#A0E2BD",
               seen_ok   = "#A0E2BD",
               seen_with_signs = "#E94B25",
               missed          = "#020202"),
                
    labels = c(seen            = "Vu",
               not_seen        = "Absent",
               not_performed   = "Pas d'action",
               # seen_no_signs   = "Vu sans signes",
               seen_ok  = "Vu sans signes",
               seen_with_signs = "Vu avec signes",
               missed          = "Décédé"))


statuscols <- c(missed = 0, 
                seen_with_signs = 0, 
                # seen_no_signs = 0,
                seen_ok=0,
                not_seen = 0,
                not_performed = 0)

completioncols <- c(completed = 0,
                    partial = 0,
                    not_attempted = 0)

scale_completion <- scale_fill_manual(
  name = "Completed",
  values = c("#E94B25",
             "#ABADAB"),
  
  labels = c("Incomplete",
             "Completed"))

scale_risk_factors <- scale_fill_manual(
  name = "Status",
  values = c("#ff5c33",
             "#c2d6d6",
             custom_grey0),
  
  labels = c("Yes",
             "No",
             "Unknown"))

```

```{r define_time_periods, include = FALSE}

today=Sys.Date()-1 #RDN-X

prev_1_date <- today - 1
prev_7_date <- prev_1_date - 7
prev_21_date <- prev_1_date - 21

# Create data of these time points, by filtering follow up list for only these date ranges 
f_1day <- current_clean_followups %>% 
  filter(date_of_followup == prev_1_date) %>% 
  mutate(days = as.character(prev_1_date)) 

f_0day <- current_clean_followups %>%
  filter(date_of_followup == today) %>% 
  mutate(days = as.character(today)) 

f_7day <- current_clean_followups %>%
  filter(date_of_followup >= prev_7_date) %>% 
  mutate(days = as.character(prev_7_date)) 

f_21day <- current_clean_followups %>%
  filter(date_of_followup >= prev_21_date) %>% 
  mutate(days = as.character(prev_21_date)) 

```

```{r linelists, include = FALSE}

## Join followups to team to have name
df_teams_tempo <- current_teams %>%
  rename(team_id=uuid, team_name=name)

followups_with_teams_names <- left_join(current_clean_followups,df_teams_tempo, by=c("team_id")) %>%
  select(
    contact_id,
    contact_uuid,
    date_of_followup,
    seen,
    followup_status,
    followup_number,
    performed,
    updated_at=updatedAt,
    team_name,
    team_id,
    fosa=admin_4_name,
    sous_prefecture=admin_3_name,
    prefecture=admin_2_name,
    region=admin_1_name
  )


## daily follow ups, past 21 days
daily_follow_up_linelist_21d <- followups_with_teams_names %>%
  arrange(desc(date_of_followup)) %>%
  select(date_of_followup,
         contact_id,
         contact_uuid,
         followup_status,
         seen,
         team_name,
         team_id,
         fosa,
         sous_prefecture,
         prefecture,
         region,
         followup_number,
         performed,
         updated_at
         )

fu_subset <- daily_follow_up_linelist_21d %>%
  filter(date_of_followup == today |
         date_of_followup == prev_1_date) %>%
  arrange(contact_id, desc(updated_at)) %>%
  distinct(contact_id, .keep_all = TRUE)

contact_status_linelist <- 
  left_join(current_clean_contacts,fu_subset, by = c("uuid"="contact_uuid")) %>%
  select(
    contact_id=contact_id.x,
    statut_followup = followup_status,
    full_name,
    sexe = gender,
    age,
    classe_age = age_class,
    occupation,
    date_dernier_contact = date_of_last_contact,
    date_dernier_visite = date_of_followup,
    date_contact_liste = date_of_data_entry,
    fosa = fosa.x,
    sous_prefecture = sous_prefecture.x,
    prefecture = prefecture.x,
    region=region.x,
    team_name,
    contact_status,
    seen,
    # enterrement_securise = safeburial,
    # statut_dernier_visite = status,
    # statut_vaccinal = vaccinated,
    etait_cas = was_case) 



```



COURBE EPIDEMIQUE {data-icon="fa-chart-line"}
=====================================================
Column {data-width=7%}
-------------------------------------

### Total Cases
```{r total_cases_reg1, echo = FALSE}

total_cases_reg <- current_clean_cases %>%
  count()

valueBox(total_cases_reg, 
          # icon = "fa-user-plus", 
         caption = "Cas",
         color = godata_orange)

```

### Total vivants
```{r total_cas_vivants1, echo = FALSE}

total_cas_vivants <- current_clean_cases %>%
  filter(outcome_id=='vivant') %>%
  count()

valueBox(total_cas_vivants, 
         # icon = "fa-user-plus", 
         caption = "vivants",
         color = godata_green)

```


### Total EDS
```{r total_eds1, echo = FALSE}

total_cas_eds <- current_clean_cases %>%
  filter(outcome_id=='EDS') %>%
  count()

valueBox(total_cas_eds, 
         # icon = "fa-user-plus", 
         caption = "EDS",
         color = "#F9D173")

```

### Total nonEDS
```{r total_noneds1, echo = FALSE}

total_cas_noneds <- current_clean_cases %>%
  filter(outcome_id=='pas de EDS') %>%
  count()

valueBox(total_cas_noneds, 
         # icon = "fa-user-plus", 
         caption = "pas de EDS",
         color = "#824427")

```

### Total retabli
```{r total_retabli1, echo = FALSE}

total_cas_retabli <- current_clean_cases %>%
  filter(outcome_id=='rétabli') %>%
  count()

valueBox(total_cas_retabli, 
         # icon = "fa-user-plus", 
         caption = "rétabli",
         color = "#B7D5DF")

```

### Total contacts
```{r total_contacts1, echo = FALSE}

total_cas_contacts <- current_clean_contacts %>%
  count()

valueBox(total_cas_contacts, 
         # icon = "fa-user-plus", 
         caption = "Contacts",
         color = custom_blue)

```

### Total contacts suivis
```{r total_contacts_suivis1, echo = FALSE}

total_cas_contacts_suivis <- current_clean_contacts %>%
  filter(contact_status=='UNDER_FOLLOW_UP') %>%
  count()

valueBox(total_cas_contacts_suivis, 
         # icon = "fa-user-plus", 
         caption = "Contacts sous suivi",
         color = custom_blue0)

```

Column {data-width=50%}
-------------------------------------
### courbe épidémique

```{r courbe_epidemique,fig.width=10, fig.height=7}

df_courbe=current_clean_cases %>% 
  filter() %>%
  count(date_of_onset,classification, sort = TRUE) 
  # tail(15)

df_courbe <- na.omit(df_courbe) #Remove all rows contents NA

df_courbe$date_of_onset <- as.character(df_courbe$date_of_onset) #Convert date field to string
  
p1=ggplot(df_courbe, aes(x=date_of_onset, y=n, fill=classification)) +
geom_bar(stat="identity") +
  theme_classic() +
  xlab("") + ylab("nombre de cas") + labs(fill="") +
  ggtitle("courbe épidémique des cas confirmés de MVE") +
  theme(plot.title = element_text(color="#666666", size=11)) +theme(axis.text.x = element_text(angle = 40, hjust = 1)) +
  scale_fill_manual(values=c('#7D0633','#4E89AE','#8D93AB','#E8FFC1'))

p1

```

CAS {data-icon="fas fa-user"} 
=====================================================

Column {data-width=7%}
-------------------------------------

### Total Cases
```{r total_cases_reg, echo = FALSE}

total_cases_reg <- current_clean_cases %>%
  count()

valueBox(total_cases_reg, 
          # icon = "fa-user-plus", 
         caption = "Cas",
         color = godata_orange)

```

### Total vivants
```{r total_cas_vivants, echo = FALSE}

total_cas_vivants <- current_clean_cases %>%
  filter(outcome_id=='vivant') %>%
  count()

valueBox(total_cas_vivants, 
         # icon = "fa-user-plus", 
         caption = "vivants",
         color = godata_green)

```

### Total EDS
```{r total_eds, echo = FALSE}

total_cas_eds <- current_clean_cases %>%
  filter(outcome_id=='EDS') %>%
  count()

valueBox(total_cas_eds, 
         # icon = "fa-user-plus", 
         caption = "EDS",
         color = "#F9D173")

```

### Total nonEDS
```{r total_noneds, echo = FALSE}

total_cas_noneds <- current_clean_cases %>%
  filter(outcome_id=='pas de EDS') %>%
  count()

valueBox(total_cas_noneds, 
         # icon = "fa-user-plus", 
         caption = "pas de EDS",
         color = "#824427")

```

### Total retabli
```{r total_retabli, echo = FALSE}

total_cas_retabli <- current_clean_cases %>%
  filter(outcome_id=='rétabli') %>%
  count()

valueBox(total_cas_retabli, 
         # icon = "fa-user-plus", 
         caption = "rétabli",
         color = "#B7D5DF")

```

### Total contacts
```{r total_contacts, echo = FALSE}

total_cas_contacts <- current_clean_contacts %>%
  count()

valueBox(total_cas_contacts, 
         # icon = "fa-user-plus", 
         caption = "Contacts",
         color = custom_blue)

```

### Total contacts suivis
```{r total_contacts_suivis, echo = FALSE}

total_cas_contacts_suivis <- current_clean_contacts %>%
  filter(contact_status=='UNDER_FOLLOW_UP') %>%
  count()

valueBox(total_cas_contacts_suivis, 
         # icon = "fa-user-plus", 
         caption = "Contacts sous suivi",
         color = custom_blue0)

```

Column {data-width=47%}
-------------------------------------
### répartition par tranches d’âge
```{r notification,fig.width=9, fig.height=4}

notification_cases=current_clean_cases %>% 
  filter(outcome_id=='décédé' | outcome_id=='vivant'  | outcome_id=='EDS'  | outcome_id=='pas de EDS') %>%
  count(age_class,outcome_id, sort = TRUE) 
  
notification_cases <- na.omit(notification_cases) #Remove all rows contents NA
#reverse order of age_class in chart
notification_cases$age_class <- factor(notification_cases$age_class, levels = rev(levels(notification_cases$age_class))) 

p1=ggplot(data=notification_cases, aes(x=age_class, y=n, fill=outcome_id)) +
geom_bar(stat="identity", position=position_dodge()) +
  theme_classic()+scale_fill_manual(values = c('#ED6663', '#FFA372',"#43658B","#4E89AE","#E3DFC8")) +
  xlab("Tranche d'age") + ylab("Nombre de cas et décès") + labs(fill="") +
  ggtitle("Répartition par tranches d’âge des cas confirmés et des cas probables de MVE") +
  theme(plot.title = element_text(color="#666666", size=11))

p1

```


### pyramide des âges
```{r}
library(dplyr)
library(ggplot2)
library(scales)
library(gganimate)
library(ggpol)

case_age_sex_breakdown <- current_clean_cases %>%
  filter(age_class != "unknown") %>%
  filter(!is.na(gender)) %>%
  group_by(gender, age_class) %>%
  summarise(num = n()) %>%
  ungroup() %>%
  mutate(prop_case = round(num / sum(num) * 100,2)) 

# case_age_sex_breakdown$age_class <- factor(case_age_sex_breakdown$age_class, levels = c("0-4","5-9","10-14","15-19","20-29","30-39","40-49","50-59","60-64","65-69","70-74","75-79","80+")) 

#reverse order of age_class in chart from 0-4 to 80+
case_age_sex_breakdown$age_class <- factor(case_age_sex_breakdown$age_class, levels = rev(levels(case_age_sex_breakdown$age_class))) 

#create population pyramid
g <- ggplot(case_age_sex_breakdown, aes(x = age_class, fill = gender,
                 y = ifelse(test = gender == "homme",
                            yes = num, no = -num))) + 
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = abs, limits = max(case_age_sex_breakdown$num) * c(-1,1)) +
    labs(title = "", x = "tranche d'âge", y = "proportion") +
  scale_colour_manual(values = c("pink", "steelblue"),
                      aesthetics = c("colour", "fill")) + theme_classic()+
  coord_flip()
g

```



Column {data-width=46%}
-------------------------------------
### repartition par sexe
```{r rep_sexe}
df_sexe=current_cases_probables_confirmes  %>%
   count(gender) %>%
   rename(sexe=gender)

df_sexe <- na.omit(df_sexe) #Remove all rows contents NA
df_sexe <- df_sexe %>%
  mutate(pro=round((n/sum(df_sexe$n))*100,1))

# Create a basic bar
pie = ggplot(df_sexe, aes(x="", y=n, fill=sexe)) + geom_bar(stat="identity", width=1)
pie = pie + coord_polar("y", start=0) + geom_text(aes(label = paste0(pro, "%")), position = position_stack(vjust = 0.5))
pie = pie + scale_fill_manual(values=c("#CD534CFF","#0073C2FF","#EFC000FF" )) 
pie = pie + labs(x = NULL, y = NULL, fill = NULL, title = "Répartition par sexe, cas confirmés et probables de MVE")
# Tidy up the theme
pie = pie + theme_classic() + theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#666666"))
pie

```

### répartition par statut
```{r rep-statut}
df_statut=current_cases_probables_confirmes  %>%
  count(outcome_id) %>%
  rename(statut=outcome_id)

df_statut <- na.omit(df_statut) #Remove all rows contents NA
df_statut <- df_statut %>%
  mutate(pro=round((n/sum(df_statut$n))*100,1))


# Create a basic bar
pie = ggplot(df_statut, aes(x="", n, fill=statut)) + geom_bar(stat="identity", width=1)
pie = pie + coord_polar("y", start=0) + geom_text(aes(label = paste0((pro), "%")), position = position_stack(vjust = 0.5))
pie = pie + scale_fill_manual(values=c("#CD534CFF","#0073C2FF","#824427","#EFC000FF" )) 
pie = pie + labs(x = NULL, y = NULL, fill = NULL, title = "Répartition par statut, cas confirmés et probables de MVE")
# Tidy up the theme
pie = pie + theme_classic() + theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#666666"))
pie
```


CONTACTS {data-icon="fas fa-users"}
=====================================================

Column {data-width=30%}
-------------------------------------

### rep - refecture
```{r repartition-contacts-prefectures}

library(ggplot2)

g <- ggplot(current_clean_contacts) +
 aes(x = prefecture) +
 geom_bar(fill = "#31688e") +
 labs(y = "effectifs", x="", title = "répartition de contacts par prefecture")  +
 theme_classic()+ theme(axis.text.x = element_text(angle = 40, hjust = 1)) + theme(plot.title = element_text(color="#666666", size=11))
g

```

### rep - age
```{r repartition-contacts-class-age}

library(ggplot2)

g <- ggplot(current_clean_contacts) +
 aes(x = age_class) +
 geom_bar(fill = "#26828e") +
 labs(x = "tranche d'âge", title = "répartion des contacts par tranche d'âge") +
 coord_flip() +
 theme_classic()
g

```

Column {.tabset data-width=70%}
-------------------------------------
### Situation du suivi des contacts
```{r}

tab4a <- current_clean_followups %>%
  distinct(contact_uuid,admin_2_name) %>%
  count(admin_2_name, sort = TRUE) %>%
  rename(localite=admin_2_name, contacts_a_suivre=n)

tab4b <- current_clean_followups %>%
  filter(followup_status !="NOT_PERFORMED" & date_of_data_entry <= today ) %>%
  distinct(contact_uuid,admin_2_name) %>%
  count(admin_2_name, sort = TRUE) %>%
  rename(localite=admin_2_name, contacts_suivis=n)

tab4c <- current_clean_followups %>%
  filter(followup_status =="NOT_PERFORMED" & date_of_data_entry <= today ) %>%
  distinct(contact_uuid,admin_2_name) %>%
  count(admin_2_name, sort = TRUE) %>%
  rename(localite=admin_2_name, contacts_nonsuivis=n)

tab_taux=left_join(tab4a,tab4b,by= c("localite"))
tab_taux=tab_taux %>%
  mutate(taux_suivi_contact=ifelse(!is.na(contacts_suivis),paste0(round((tab_taux$contacts_suivis/tab_taux$contacts_a_suivre)*100,1)," %"),"0 %"))
tab_gen=left_join(tab_taux,tab4c,by= c("localite"))

tab_new_contacts_today <- current_clean_contacts %>%
    filter(date_of_data_entry == today ) %>%
  distinct(uuid,prefecture) %>%
  count(prefecture, sort = TRUE) %>%
  rename(localite=prefecture, nouveaux_contacts=n)
tab_gen=tab_gen=left_join(tab_gen,tab_new_contacts_today,by= c("localite"))

tab_contacts_devenus_suspects=current_contacts_becoming_cases %>%
  filter(classification=="SUSPECT") %>%
  distinct(uuid,prefecture) %>%
  count(prefecture, sort = TRUE) %>%
  rename(localite=prefecture, contacts_devenus_suspects=n)
tab_gen=tab_gen=left_join(tab_gen,tab_contacts_devenus_suspects,by= c("localite"))
  

tab_contacts_sortis <- current_clean_contacts %>%
    filter(contact_status != "UNDER_FOLLOW_UP") %>%
  distinct(uuid,prefecture) %>%
  count(prefecture, sort = TRUE) %>%
  rename(localite=prefecture, contacts_sortis=n)
tab_gen=tab_gen=left_join(tab_gen,tab_contacts_sortis,by= c("localite"))

tab_contacts_restant <- current_clean_contacts %>%
    filter(contact_status == "UNDER_FOLLOW_UP") %>%
  distinct(uuid,prefecture) %>%
  count(prefecture, sort = TRUE) %>%
  rename(localite=prefecture, contacts_restant=n)
tab_gen=tab_gen=left_join(tab_gen,tab_contacts_restant,by= c("localite"))

tab_gen %>%
  mutate(contacts_suivis = if_else(is.na(contacts_suivis), "0", paste0(contacts_suivis,""))) %>% #replace NA by nothing
  mutate(nouveaux_contacts = if_else(is.na(nouveaux_contacts), "0", paste0(contacts_suivis,""))) %>% #replace NA by nothing
  mutate(contacts_devenus_suspects = if_else(is.na(contacts_devenus_suspects), "0", paste0(contacts_devenus_suspects,""))) %>% #replace NA by nothing
    mutate(contacts_sortis = if_else(is.na(contacts_sortis), "0", paste0(contacts_sortis,""))) %>% #replace NA by nothing
  mutate(contacts_restant = if_else(is.na(contacts_restant), "0", paste0(contacts_restant,""))) %>% #replace NA by nothing
  kbl( caption = "", align=c(rep('c',times=8)),
       col.names = c("Localité","Contacts à suivre","Contacts suivis","Taux de suivi","Contacts non suivis", 
"Nouv. contacts à ce jour","contacts devenus suspects","Contacts sortis du suivi","Contacts restant")) %>%
   kable_styling(font_size = 14,fixed_thead = T,bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1:9, width = "5em", bold = TRUE, italic = TRUE)

```

### Situation quotidienne des contacts par équipe

```{r situation_quot_contacts_par_equipe, fig.width=10, fig.height=7}

contact_status_by_team <- contact_status_linelist %>%
  filter(! is.na(team_name)) %>%
  mutate(team_name = str_replace_all(team_name, "_", " ")) %>%
  mutate(team_name = str_to_title(team_name)) %>%
  mutate(prefecture = str_to_title(prefecture)) %>%
  filter(date_dernier_visite == today) %>% 
  group_by(team_name, prefecture,statut_followup) %>%
  tally() %>%
  mutate(statut_followup=tolower(statut_followup))%>%
  pivot_wider(names_from = statut_followup, values_from = n, values_fill = list(n=0)) %>%
  add_column(!!!statuscols[!names(statuscols)%in% names(.)]) %>% #cheick and complete columns
  gather("daily_status", "n", -team_name, -prefecture) %>%
  arrange(team_name, prefecture, daily_status)


graph_contact_status_by_team <- contact_status_by_team %>%
    ggplot(aes(x = reorder(team_name, n), y = n, fill = daily_status, label = ifelse(n>0, n, NA))) +
    geom_col(position = "stack") +
    theme_classic() +
    labs(x = "",
         y = "Nombre de contacts",
         title = "Statut de contacts quotidien, par équipe",
         subtitle = paste0("Données du ", today, "\n")) +
  theme(plot.title = element_text(face = "bold", color = "#011822", size = 14),
        plot.subtitle = element_text(size = 11, color = "#011822")
        # ,legend.position = "top"
        ) +
  facet_wrap(~prefecture, strip.position = "right", scales = "free_y", ncol = 1) +
  geom_text(size = 3, position = position_stack(vjust = 0.5), color = "white", check_overlap = TRUE, fontface = "bold") +
  geom_hline(aes(yintercept=25), color="#C70039", linetype="dashed")+
  scale_status +
    coord_flip()


graph_contact_status_by_team
```






LISTE DE LIGNES - INDICATEURS {data-icon="fa-list"} 
=====================================================
Column {.tabset data-width=100%}
-------------------------------------
### Demographique

```{r, echo = FALSE}
format_tab_demographics
```

### Taxonomie

```{r, echo = FALSE}

```
  
### Surveillance

```{r, echo = FALSE}

```
 
### Vaccination

```{r, echo = FALSE}

```

### PCI

```{r, echo = FALSE}

```

### Laboratoire

```{r, echo = FALSE}

```

