library(shiny)
library(shinydashboard)
library(shinycustomloader)
library(ggplot2)
library(plotly)
library(tidyr)
library(dplyr)
library(readr)
library(kableExtra)
library(tibble)
library(janitor)
library(caTools)
library(DT)
library(RColorBrewer)
library(leaflet)
library(sf)
library(htmltools)
library(scales)
library(lubridate)
library(forcats)
library(zoo)
library(stringr)
library(writexl)
library(data.table)


Sys.setenv(TZ='America/Guatemala')
options(shiny.maxRequestSize = 30*1024^2)

